const facialExpressionMapping = {
    'Grinning Face': '😀',
    'Grinning Face With Big Eyes': '😃',
    'Grinning Face With Smiling Eyes': '😄',
    'Beaming Face With Smiling Eyes': '😁',
    'Grinning Squinting Face': '😆',
    'Grinning Face With Sweat': '😅',
    'Rolling On The Floor Laughing': '🤣',
    'Face With Tears Of Joy': '😂',
    'Slightly Smiling Face': '🙂',
    'Upside-Down Face': '🙃',
    'Melting Face': '🫠',
    'Winking Face': '😉',
    'Smiling Face With Smiling Eyes': '😊',
    'Smiling Face With Halo': '😇',
    'Smiling Face With Hearts': '🥰',
    'Smiling Face With Heart-Eyes': '😍',
    'Star-Struck': '🤩',
    'Face Blowing A Kiss': '😘',
    'Kissing Face': '😗',
    'Kissing Face With Closed Eyes': '😚',
    'Kissing Face With Smiling Eyes': '😙',
    'Face Savoring Food': '😋',
    'Face With Tongue': '😛',
    'Winking Face With Tongue': '😜',
    'Zany Face': '🤪',
    'Squinting Face With Tongue': '😝',
    'Money-Mouth Face': '🤑',
    'Smiling Face With Open Hands': '🤗',
    'Face With Hand Over Mouth': '🤭',
    'Face With Open Eyes And Hand Over Mouth': '🫢',
    'Face With Peeking Eye': '🫣',
    'Shushing Face': '🤫',
    'Thinking Face': '🤔',
    'Saluting Face': '🫡',
    'Zipper-Mouth Face': '🤐',
    'Face With Raised Eyebrow': '🤨',
    'Neutral Face': '😐',
    'Expressionless Face': '😑',
    'Face Without Mouth': '😶',
    'Face In Clouds': '😶‍🌫️',
    'Smirking Face': '😏',
    'Unamused Face': '😒',
    'Face With Rolling Eyes': '🙄',
    'Grimacing Face': '😬',
    'Face Exhaling': '😮‍💨',
    'Lying Face': '🤥',
    'Relieved Face': '😌',
    'Pensive Face': '😔',
    'Sleepy Face': '😪',
    'Drooling Face': '🤤',
    'Sleeping Face': '😴',
    'Face With Medical Mask': '😷',
    'Face With Thermometer': '🤒',
    'Face With Head-Bandage': '🤕',
    'Nauseated Face': '🤢',
    'Face Vomiting': '🤮',
    'Sneezing Face': '🤧',
    'Hot Face': '🥵',
    'Cold Face': '🥶',
    'Woozy Face': '🥴',
    'Face With Crossed-Out Eyes': '😵',
    'Face With Spiral Eyes': '😵‍💫',
    'Exploding Head': '🤯',
    'Cowboy Hat Face': '🤠',
    'Partying Face': '🥳',
    'Disguised Face': '🥸',
    'Smiling Face With Sunglasses': '😎',
    'Nerd Face': '🤓',
    'Face With Monocle': '🧐',
    'Confused Face': '😕',
    'Face With Diagonal Mouth': '🫤',
    'Worried Face': '😟',
    'Slightly Frowning Face': '🙁',
    'Face With Open Mouth': '😮',
    'Hushed Face': '😯',
    'Astonished Face': '😲',
    'Flushed Face': '😳',
    'Pleading Face': '🥺',
    'Face Holding Back Tears': '🥹',
    'Frowning Face With Open Mouth': '😦',
    'Anguished Face': '😧',
    'Fearful Face': '😨',
    'Anxious Face With Sweat': '😰',
    'Sad But Relieved Face': '😥',
    'Crying Face': '😢',
    'Loudly Crying Face': '😭',
    'Face Screaming In Fear': '😱',
    'Confounded Face': '😖',
    'Persevering Face': '😣',
    'Disappointed Face': '😞',
    'Downcast Face With Sweat': '😓',
    'Weary Face': '😩',
    'Tired Face': '😫',
    'Yawning Face': '🥱',
    'Face With Steam From Nose': '😤',
    'Enraged Face': '😡',
    'Angry Face': '😠',
    'Face With Symbols On Mouth': '🤬',
    'Smiling Face With Horns': '😈',
    'Angry Face With Horns': '👿'
}

function getNewFacialExpression() {
    var keys = Object.keys(facialExpressionMapping);
    var randomKey = keys[keys.length * Math.random() << 0];
    var randomObj = facialExpressionMapping[randomKey];
    return [randomKey, randomObj];
}
